### ISSUE TITLE
suspending function firestore#collection#add hangs

### ISSUE THREAD

**Issue by vanniktech** [GitLiveApp/firebase-kotlin-sdk#75] opened 2020-08-09 04:54 UTC
Every now and then - maybe about 10% of the times - the following code just hangs:

```
override fun createTask(title: String, callback: (SuccessFailure<Unit>) -> Unit) = MainScope().launch {
  try {
    val task = FireStoreTodoTask(
        title = title
    )

    val path = "${list.path}/tasks"
    logI(TAG, "On $path creating task $task")
    firebaseStore.collection(path).add(task, FireStoreTodoTask.serializer())
    logI(TAG, "Creating task succeeded")
    callback.invoke(Success(Unit))
  } catch (throwable: Throwable) {
    logI(TAG, "Creating task failed", throwable)
    callback.invoke(Failure(TAG, throwableReasonConverter.convert(throwable)))
  }
}
```

After `firebaseStore.collection(path).add(task, FireStoreTodoTask.serializer())` nothing happens. The suspend function just keeps running. Neither end I up in the next line nor I get thrown at.

Has anyone else been experiencing this?

**Comment by vanniktech** [comment] 2020-08-09 04:57
Oh this is with an intermediate version of 0.1.0 & 0.2.0 on an Android phone.

**Comment by vanniktech** [comment] 2020-08-15 06:39
Yesterday I just let it ran and continue (a loading dialog is displayed):

```
2020-08-13 21:20:08:819 I/Interactor Show dialog
2020-08-13 21:21:36:872 I/Interactor Hide dialog
```

It took 1.5 minutes to get a callback from the suspend functiion.

**Comment by nbransby** [comment] 2020-08-20 20:36
Don't know what this could be but my guess is its blocking in [Task<T>.await()](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-play-services/kotlinx.coroutines.tasks/com.google.android.gms.tasks.-task/await.html) . Using the new corountines debugger might help figure out whats going on.

Also you could use .android and implement it in pure android, if it still happens then at least we can rule out the SDK.

**Comment by rocketraman** [comment] 2021-02-09 06:56
I can reproduce a hang with Realtime Database (recognizing that OP is posting about FireStore, perhaps its the same root cause?), simply by reading a path which contains hundreds of keys and attempting to collect them into a list:

```
    db.reference("k").childEvents(ChildEvent.Type.ADDED)
      .mapNotNull {
        val key = it.snapshot.key
        println("Key=$key")
        key
      }
      .toList()
```

The "Key=" output is seen in the console for about 20 or 30 keys, and then the flow hangs.

The thread dump shows FirebaseDatabaseWorker seems to be hung with this stack:

```
"FirebaseDatabaseWorker@21538" daemon prio=5 tid=0x2cc nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.google.firebase.database.snapshot.ChildrenNode.isEmpty(ChildrenNode.java:102)
	  at com.google.firebase.database.snapshot.ChildrenNode.hasChild(ChildrenNode.java:97)
	  at com.google.firebase.database.core.view.filter.IndexedFilter.updateFullNode(IndexedFilter.java:97)
	  at com.google.firebase.database.core.view.ViewProcessor.generateEventCacheAfterServerEvent(ViewProcessor.java:219)
	  at com.google.firebase.database.core.view.ViewProcessor.listenComplete(ViewProcessor.java:669)
	  at com.google.firebase.database.core.view.ViewProcessor.applyOperation(ViewProcessor.java:156)
	  at com.google.firebase.database.core.view.View.applyOperation(View.java:173)
	  at com.google.firebase.database.core.SyncPoint.applyOperationToView(SyncPoint.java:78)
	  at com.google.firebase.database.core.SyncPoint.applyOperation(SyncPoint.java:109)
	  at com.google.firebase.database.core.SyncTree.applyOperationDescendantsHelper(SyncTree.java:970)
	  at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:901)
	  at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:920)
	  at com.google.firebase.database.core.SyncTree.applyOperationToSyncPoints(SyncTree.java:887)
	  at com.google.firebase.database.core.SyncTree.access$400(SyncTree.java:76)
	  at com.google.firebase.database.core.SyncTree$7.call(SyncTree.java:374)
	  at com.google.firebase.database.core.SyncTree$7.call(SyncTree.java:370)
	  at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(NoopPersistenceManager.java:126)
	  at com.google.firebase.database.core.SyncTree.applyListenComplete(SyncTree.java:369)
	  at com.google.firebase.database.core.SyncTree$ListenContainer.onListenComplete(SyncTree.java:135)
	  at com.google.firebase.database.core.Repo$4$1.onRequestResult(Repo.java:191)
	  at com.google.firebase.database.connection.PersistentConnectionImpl$5.onResponse(PersistentConnectionImpl.java:1106)
	  at com.google.firebase.database.connection.PersistentConnectionImpl.onDataMessage(PersistentConnectionImpl.java:406)
	  at com.google.firebase.database.connection.Connection.onDataMessage(Connection.java:164)
	  at com.google.firebase.database.connection.Connection.onMessage(Connection.java:128)
	  at com.google.firebase.database.connection.WebsocketConnection.appendFrame(WebsocketConnection.java:257)
	  at com.google.firebase.database.connection.WebsocketConnection.handleIncomingFrame(WebsocketConnection.java:304)
	  at com.google.firebase.database.connection.WebsocketConnection.access$500(WebsocketConnection.java:34)
	  at com.google.firebase.database.connection.WebsocketConnection$WSClientTubesock$2.run(WebsocketConnection.java:86)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	  at java.lang.Thread.run(Thread.java:923)
```

When using `.android` to implement the code in pure Android, it loops through all the keys without hanging:

```
    db.reference("k").android.addChildEventListener(object : ChildEventListener {
      override fun onChildAdded(snapshot: DataSnapshot, previousChildName: String?) {
        snapshot.key?.let {
          println("Key=$it")
          l.add(it)
        }
      }

      override fun onChildChanged(snapshot: DataSnapshot, previousChildName: String?) {
      }

      override fun onChildRemoved(snapshot: DataSnapshot) {
      }

      override fun onChildMoved(snapshot: DataSnapshot, previousChildName: String?) {
      }

      override fun onCancelled(error: DatabaseError) {
      }
    })
```

Here, the `Key=` output is seen for all the keys.

**Comment by nbransby** [comment] 2021-02-09 07:55
This is the expected behaviour, the flows are hot and will wait forever for new changes from Firebase until you cancel the coroutine you collected it from. 

Same goes for the listener you added via . android it's still listening until you remove it.

**Comment by rocketraman** [comment] 2021-02-09 08:12
> the flows are hot and will wait forever for new changes from Firebase until you cancel the coroutine you collected it from.

Really? Flows in Kotlin are supposed to be cold. I wouldn't expect a terminal operator like `toList` on a Flow to just hang waiting forever. The correct Kotlin primitive to use for a hot data source is a `Channel`. See https://elizarov.medium.com/cold-flows-hot-channels-d74769805f9.

**Comment by nbransby** [comment] 2021-02-09 08:20
Yeah that is quite an old post, check out some other examples of hot flows in the API:
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-shared-flow/index.html

But technically our flows are still cold in the sense they only start once you collect them and collecting them again will create a new separate listener, for more info see:
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/callback-flow.html

**Comment by rocketraman** [comment] 2021-02-09 09:05
A SharedFlow is a specialization of Flow. What applies to it does not apply to Flows in general.

If the SDK returned a SharedFlow then the argument could be valid, but I don't think that's the right abstraction either. SharedFlow is supposed to replace BroadcastChannel, not Channel (or Flow).

**Comment by nbransby** [comment] 2021-02-09 12:01
Yes it is a specialization but it's a Flow meaning you could pass it as just a Flow hence flows can be hot.

In fact your example code highlights exactly why this flow should be hot and never complete. You are subscribing to child added events for the reference "k". That means whenever a child is added under k you will receive an event, forever. You don't specify how many events to wait for (e.g .take(5)) or how long to wait for therefore it will never complete just like the listener will never stop listening in the .android version

**Comment by rocketraman** [comment] 2021-02-09 13:08
> Yes it is a specialization but it's a Flow meaning you could pass it as just a Flow hence flows can be hot

That's true. The Flow docs need a serious updating. There is a whole [section](https://kotlinlang.org/docs/reference/coroutines/flow.html#flows-are-cold) called "Flows are cold" which is clearly wrong.

**Comment by nbransby** [comment] 2021-02-09 13:13
Yes the SharedFlow stuff is a very recent addition

**Comment by rocketraman** [comment] 2021-02-09 13:37
Sorry for "polluting" this isue with unrelated discussion, but just to close it off, @nbransby what is the best way given the hot `Flow` abstraction, to obtain all the keys that exist right now and no more? Essentially the equivalent of `addListenerForSingleValueEvent`. See:

https://firebase.google.com/docs/database/android/read-and-write#read_data_once
https://firebase.google.com/docs/reference/android/com/google/firebase/database/Query#addListenerForSingleValueEvent(com.google.firebase.database.ValueEventListener)

Should I open a separate issue for a missing API surface?

**Comment by nbransby** [comment] 2021-02-09 14:23
So best way is to not use childEvents but valueEvents.first()

**Comment by rocketraman** [comment] 2021-02-09 15:08
Thanks @nbransby , a pattern like this also works if the criteria for cancellation is more complex:

```
coroutineScope {
  db.reference("whatever")
    .valueEvents
    .collect {
      // inspect snapshot, and if it meets the relevant criteria, stop listening:
    coroutineContext.cancel()
  }
}
```

Do you have a better/simpler approach for that scenario?

**Comment by nbransby** [comment] 2021-02-09 15:27
.first { it.meetsCriteria }

**Comment by nbransby** [comment] 2021-05-13 21:11
Closing as unable to reproduce, happy to reopen using a reproducible example

**Closed by nbransby** 2021-05-13 21:11 UTC
