### ISSUE TITLE
Multithreading in kotlin/native with AtomicRefernce PR!

### ISSUE THREAD

**Issue by Elkhoudiry** [GitLiveApp/firebase-kotlin-sdk#44] opened 2020-06-29 18:18 UTC
Well i've made some functions compatible with multithreading* in native/ios, but it needs to add AtomicReference class to the project
should i do PR with that or you want to keep this library clean like this.

*multithreading isn't natively support in Kotlin/Native, but when you create Workers to do some work in the background in IOS, and calling firebase kotlin sdk functions it will throw exceptions.

**Comment by nbransby** [comment] 2020-06-29 22:12
do you mean this? https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.native.concurrent/-atomic-reference/

Isn't that part of the standard lib?

**Comment by Elkhoudiry** [comment] 2020-06-29 22:26
yeah sorry i meant class, well i opened this issue since as it's mentioned in this great article
[https://dev.to/touchlab/practical-kotlin-native-concurrency-part-3-38p](url)

heavy usage of AtomicReference isn't likeable when performance is consideration.

but in my use case i was perfectly able to run `DocumentRefernce.get()` from back ground thread, waiting the result from Firebase sdk on the main thread, and getting it back to my thread. so it's working fine.

i'm trying right now to figure out how to get snapshots perform well with flow from other threads right now

**Comment by nbransby** [comment] 2020-06-29 22:42
The issue with K/N are mostly caused by the corountines library itself. We are waiting for these to be fixed by the corouties team - coming in 1.4 (see https://github.com/kotlin/kotlinx.coroutines/issues/462)

This should fix all the issues with Flow

**Comment by Elkhoudiry** [comment] 2020-06-29 22:51
i hope the flow issues will be solved, right now it's all about workarounds.
working from background is a key to make the UI responsive, so i'm trying to find workarounds for them right now.
if i success i will make a PR!

**Comment by Elkhoudiry** [comment] 2020-07-01 04:19
ok it was hellish couple of days, but now i can open flow in background and get the results in the background still,
but i'm having this weird situation.

if i right any code below `flow.collect { .. }` in the same coroutine job, that code never execute that makes me always collection the flow in another `launch { .. }` is that the normal behaviour in kotlin/native ?

code sample 
```
        val job1 = launch {
            val result = doc.frozenFlow(this)
            result.collect {
                println("thread (${mainThreadCheck()}) name is ${it?.data(FirestoreModel.serializer())?.name}")
            }
            println("here test")     // this never prints
        }
```

**Closed** 2020-07-01 16:49 UTC
